### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by ssi-kevin-muldoon** [jeremiah-de/CollectionViewSearch#1]
As of today, this project has no code.

**Comment by jeremiah-de** [comment]
@ssi-kevin-muldoon The code is contained in the branches listed in https://github.com/jeremiah-de/CollectionViewSearch/blob/master/README.md

**Comment by ssi-kevin-muldoon** [comment]
Hmm.

**Comment by jeremiah-de** [comment]
@ssi-kevin-muldoon Take a look at this branch: https://github.com/jeremiah-de/CollectionViewSearch/tree/detail

**Comment by ssi-kevin-muldoon** [comment]
Ha. I understood as soon as you mentioned branches. My ‘Hmm’ was wondering if I should be upset at myself for not reading the ReadMe file of an unpopulated code base or that the main branch was unpopulated code base. I’m 60% leaning towards being upset at myself.

**Comment by jeremiah-de** [comment]
I'll admit, the master branch should probably have been what is now the 'basic-collection-view' branch 😄
